apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: vn02cuo2d-go 
  janus-idp.io/tekton: vn02cuo2d-go
  backstage.io/kubernetes-id: vn02cuo2d-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: vn02cuo2d-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml